name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_PASS: ${{ secrets.TF_VAR_db_root_password }}

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Docker check tools
        run: sudo apt-get update

      - name: Mask DB password
        run: echo "::add-mask::$DB_PASS"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="db_root_password=$DB_PASS"

      - name: Terraform Apply
        run: terraform apply -var="db_root_password=$DB_PASS" -auto-approve

      - name: Check Web Container
        run: curl -s http://127.0.0.1:8080 | grep -q 'My First and Lastname'

      - name: Wait for MariaDB
        run: |
          echo "Waiting for MariaDB..."

          for i in {1..30}; do
            if docker exec mariadb-container mysql -uroot -p$DB_PASS -e "select 1;" 2>/dev/null; then
              echo "MariaDB is ready"
              exit 0
            fi

            echo "Attempt $i..."
            sleep 2
          done

          echo "Timeout waiting for MariaDB"
          docker logs mariadb-container
          exit 1

      - name: Check Database Container
        run: |
          docker exec mariadb-container mysql -uroot -p$DB_PASS -e "select version();"

      - name: Stop Containers
        run: docker stop $(docker ps -q)

      - name: Final Step
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh repo edit $GITHUB_REPOSITORY --visibility private --accept-visibility-change-consequences
